export { default as DashboardIcon } from './dashboard.tsx'
export { default as FinanceIcon } from './finance.tsx'
export { default as LearningIcon } from './learning.tsx'
export { default as CalendarIcon } from './calendar.tsx'
export { default as TransactionIcon } from './transaction.tsx'
